### ISSUE TITLE
Installations involving Detectron

### ISSUE THREAD

**Issue by frankvp11** [randombenj/detectron2onnx-inference#2]
Hello, I was wondering If you guys could make a "better" colab, as the one I just tried didn't suffice. When I imported detectron2 it didnt exist and had to install it myself, then it caused problems later with detectron2.export not working. Could you guys please get back to me? Thanks,
Frank

**Comment by randombenj** [comment]
As described in the notebook:
> Run this notebook inside the detectron2 repository

That said I personaly dont use detectron2 anymore but rather use torchvision directly. Feel free to submit an MR if you find better solutions or would like to do improvements ...

**Comment by frankvp11** [comment]
Alright I'll look into trying that. Thanks in advance

**Comment by frankvp11** [comment]
Hi im still getting an issue -this time it's not really with Detectron2 though
What can I do to make this work?
./datasets/prepare_for_tests.sh

gives error:
File ["<ipython-input-2-622dcc3b562c>"](https://localhost:8080/#), line 5
    ./datasets/prepare_for_tests.sh
    ^
SyntaxError: invalid syntax

**Comment by frankvp11** [comment]
Never mind, I got it all working! thanks anyways!
